version: '3.7'

services:
    web:
        build: .
        command: gunicorn main.wsgi -b 0.0.0.0:8000 --log-level DEBUG
        env_file:
            - main/.env
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db

    db:
        image: kartoza/postgis:12.1
        environment:
            POSTGRES_USER: geodjango
            POSTGRES_PASSWORD: geodjango
            POSTGRES_DBNAME: gis
        volumes:
            - postgres_data:/var/lib/postgresql/data/
volumes:
    postgres_data:

