name: "Django Tests"

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
  schedule:
    - cron: '0 4 * * 3'

jobs:
  tests:
    name: Run Django Tests
    runs-on: ubuntu-latest

    services:
      image: postgres
      env:
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
      - POSTGRES_DB: postgres
      ports:
      - 5432:5432
      options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    
    # If this run was triggered by a pull request event, then checkout the head
    # of the pull request instead of the merge commit.
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    
    # Set up Python environment
    - name: Set up Python 3.7.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.7
    
    # Set up install project dependencies
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    # Run django tests
    - name: Run Tests
      run: python manage.py test
            
