name: "Django Tests"

on:
  push:
    branches: [master, development]
  pull_request:
    branches: [master, development]
  schedule:
    - cron: '0 4 * * 3'

jobs:
  tests:
    runs-on: ubuntu-latest
    container: postgres:11

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
            fetch-depth: 2
        
    # If this run was triggered by a pull request event, then checkout the head
    # of the pull request instead of the merge commit.
      - run: git checkout HEAD^2
        if: ${{ github.event_name == 'pull_request' }}
    
      - name: Set up Python 3.8.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.5
    
      - name: Install dependencies
        run: pip install -r requirements.txt
    
      - name: Run Tests
        run: python manage.py test
            
